version: "3.9"
services:
  freeradius:
    restart: on-failure
    container_name: freeradius
    image: freeradius
    hostname: freeradius
    build:
      context: .
      dockerfile: ./services/freeradius/freeradius.dockerfile
    ports:
      - 1812-1813:1812-1813/udp
    networks:
      - freeradius

  openldap:
    restart: on-failure
    container_name: openldap
    image: openldap
    hostname: openldap
    build:
      context: .
      dockerfile: ./services/openldap/openldap.dockerfile
    ports:
      - 389:389
      - 636:636
    networks:
      - openldap
    environment:
      - LDAP_ORGANISATION=example
      - LDAP_DOMAIN=example.org
      - LDAP_ADMIN_PASSWORD=admin
    volumes:
      - ./data_persistance/backups/openldap/ldap:/var/lib/ldap
      - ./data_persistance/backups/openldap/slapd.d:/etc/ldap/slapd.d

networks:
  freeradius:
    driver: bridge
  openldap:
    driver: bridge
